# Generated by Django 4.2.11 on 2024-04-14 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Author Name')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Category Name')),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Book Name')),
                ('page_count', models.IntegerField(verbose_name='Number of Pages')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Price')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Books/', verbose_name='Book Image')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='market.author', verbose_name='Author Name')),
                ('category', models.ManyToManyField(to='market.category', verbose_name='Categories')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'ordering': ['id', 'name', 'price', 'page_count'],
                'indexes': [models.Index(fields=['id'], name='id'), models.Index(fields=['name'], name='name'), models.Index(fields=['price'], name='price'), models.Index(fields=['page_count'], name='page_count')],
            },
        ),
        migrations.AddConstraint(
            model_name='books',
            constraint=models.UniqueConstraint(fields=('id', 'name'), name='unique_book'),
        ),
    ]
