# Generated by Django 4.2.11 on 2024-04-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='author_name',
            field=models.CharField(max_length=255, verbose_name='Author Name'),
        ),
        migrations.AlterField(
            model_name='books',
            name='image',
            field=models.ImageField(upload_to='Books/', verbose_name='Book Image'),
        ),
        migrations.AlterField(
            model_name='books',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Book Name'),
        ),
        migrations.AlterField(
            model_name='books',
            name='page_count',
            field=models.IntegerField(verbose_name='Number of Pages'),
        ),
        migrations.AlterField(
            model_name='books',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Price'),
        ),
    ]
